-- MySQL Script generated by MySQL Workbench
-- 06/29/16 17:51:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LeaveApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LeaveApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LeaveApp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `LeaveApp` ;

-- -----------------------------------------------------
-- Table `LeaveApp`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`Department` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeaveApp`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`Employee` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `ContactNo` VARCHAR(45) NULL,
  `EmploymentDate` DATE NOT NULL,
  `Position` VARCHAR(45) NULL,
  `EmploymentStatus` VARCHAR(45) NOT NULL,
  `RegularizationDate` DATE NULL,
  `isSoloParent` TINYINT(1) NOT NULL,
  `VLCredits` FLOAT NULL,
  `SLCredits` FLOAT NULL,
  `ELCredits` FLOAT NULL,
  `SPCredits` FLOAT NULL,
  `OffsetCredits` FLOAT NULL,
  `isDeactivated` TINYINT NULL,
  `Department_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Employee_Department1_idx` (`Department_ID` ASC),
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `LeaveApp`.`Department` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeaveApp`.`LeaveHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`LeaveHistory` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Start` DATE NOT NULL,
  `isStartHalfDay` TINYINT(1) NULL,
  `End` DATE NOT NULL,
  `isEndHalfDay` TINYINT(1) NULL,
  `Duration` FLOAT NOT NULL,
  `DateFiled` DATETIME NOT NULL,
  `Reason` TEXT NOT NULL,
  `Status` ENUM('Pending', 'SupervisorApproved', 'HRApproved', 'Cancelled', 'Not Taken') NOT NULL,
  `LeaveType` ENUM('SL', 'VL', 'EL', 'SPL', 'OFFSET') NOT NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_LeaveHistory_Employee1_idx` (`Employee_ID` ASC),
  CONSTRAINT `fk_LeaveHistory_Employee1`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `LeaveApp`.`Employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeaveApp`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`Role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeaveApp`.`Employee_has_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`Employee_has_Role` (
  `Employee_ID` INT NOT NULL,
  `Role_ID` INT NOT NULL,
  PRIMARY KEY (`Employee_ID`, `Role_ID`),
  INDEX `fk_Employee_has_Role_Role1_idx` (`Role_ID` ASC),
  INDEX `fk_Employee_has_Role_Employee_idx` (`Employee_ID` ASC),
  CONSTRAINT `fk_Employee_has_Role_Employee`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `LeaveApp`.`Employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Role_Role1`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `LeaveApp`.`Role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeaveApp`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeaveApp`.`Comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Comment` TEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `LeaveHistory_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `LeaveHistory_ID`),
  INDEX `fk_Comments_LeaveHistory1_idx` (`LeaveHistory_ID` ASC),
  CONSTRAINT `fk_Comments_LeaveHistory1`
    FOREIGN KEY (`LeaveHistory_ID`)
    REFERENCES `LeaveApp`.`LeaveHistory` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
